#! /bin/bash
set -e

PLUGIN="$(basename $(pwd))"
SHORTNAME="${PLUGIN#Kaleidoscope-}"
HELPERS="$(dirname $(readlink -f $0))/helpers"

if ! git checkout -b f/monorepo-2 f/monorepo 2>/dev/null; then
    git checkout master
    git branch -D f/monorepo-2
    git checkout -b f/monorepo-2 f/monorepo
fi

find doc/plugin -name '*.md' | xargs -n 1 ${HELPERS}/monorepo-doc-update.pl

git add doc

git commit -s -m "Update the documentation links

Updates the example and dependency links in the documentation, to use URLs that
are valid within the monorepo."

git checkout f/monorepo
git cherry-pick f/monorepo-2
git branch -D f/monorepo-2
