#! /bin/sh
set -e
plugin=$(basename $(pwd))
desc=$(grep sentence= library.properties | cut -d= -f2-)
start_date=$(git log --date=format:%Y --format=tformat:%ad | sort -u | head -n 1)
end_date=$(git log --date=format:%Y --format=tformat:%ad | sort -u | tail -n 1)
(cat <<EOF
0i
/* ${plugin} - ${desc}
 * Copyright (C) ${start_date}-${end_date}  Keyboard.io, Inc.
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>.
 */
.
w
q
EOF
) | ed -s $1
