#! /bin/sh
set -e

HELPERS="$(dirname $(readlink -f $0))/helpers"

# Do we need a branch?
if ! git rev-parse f/license-update-and-contributing >/dev/null 2>/dev/null; then
    git checkout -b f/license-update-and-contributing
fi

case "$1" in
    license-update)
        if [ -e "LICENSE" ]; then
            license_file="LICENSE"
        else
            license_file="COPYING"
        fi

        ## GPLv3-only
        find . -name '*.ino' -or -name '*.cpp' -or -name '*.h' -or -name 'library.properties' | xargs -n1 ${HELPERS}/license-update
        cp /usr/share/common-licenses/GPL-3 $license_file
        git add .
        git commit -s -m "Relicense under the GPLv3 (only)" -S
        ;;

    copyright-reassign)
        if grep -q algernon@keyboard.io library.properties; then
            exit 0
        fi

        find . -name '*.ino' -or -name '*.cpp' -or -name '*.h' -or -name 'library.properties' | xargs -n1 ${HELPERS}/copyright-assignment
        git add .
        git commit -s -m "Assign my copyright to Keyboard.io

While the original plugin was written independently, significant developments
were made while working for Keyboard.io. As such, I feel it is appropriate to
assign copyright to the company." -S || true
        ;;

    contributing)
        cp ../Kaleidoscope/CONTRIBUTING.md .
        git add .
        git commit -s -m "Add CONTRIBUTING.md

Copied from Kaleidoscope, as it is applicable here too." -S
        ;;

    license-gpl3)
        if [ -e "LICENSE" ]; then
            license_file="LICENSE"
        else
            license_file="COPYING"
        fi

        if grep -q "Version 2, June 1991" $license_file; then
            was_gpl2=1
        else
            was_gpl2=0
        fi

        cp /usr/share/common-licenses/GPL-3 $license_file

        find . -name '*.ino' -or -name '*.cpp' -or -name '*.h' | xargs -n1 ${HELPERS}/license-gpl3
        git add .

        if [ $was_gpl2 -eq 1 ]; then
            git commit -s -m "Relicense under GPLv3 (only), and add headers." -S
        else
            git commit -s -m "Add copyright & license headers" -S
        fi
        ;;

    pull-request)
        subject=""
        body="This"
        if git log --format=tformat:%s master.. | grep -q "Relicense"; then
            subject="License clarification"
            body="${body} changes the license to GPLv3 (only) and updates the copyright & license notices in every affected file"
        fi
        if git log --format=tformat:%s master.. | grep -q "Assign my copyright"; then
            if [ -z "$subject" ]; then
                subject="Copyright assignment"
                body="${body} assigns my copyright to Keyboard.io Inc"
            else
                subject="${subject}, copyright assignment"
                body="${body}; assigns my copyright to Keyboard.io, Inc"
            fi
        fi
        if git log --format=tformat:%s master.. | grep -q "CONTRIBUTING.md"; then
            if [ -z "${subject}" ]; then
                subject="Add CONTRIBUTING.md"
                body="${body} adds a CONTRIBUTING.md"
            else
                subject="${subject} & CONTRIBUTING.md"
                body="${body}; and adds a CONTRIBUTING.md"
            fi
        fi

        body="$(echo "${body}" | fold -s)."

        git push origin HEAD -u
        hub pull-request -r obra -m "${subject}

${body}" --edit
        ;;

esac
